### ISSUE TITLE
'npm install' not working.

### ISSUE THREAD

**Issue by christmerlini** [coursefiles/angular2-essential-training#5]
Hi Justin,

I just started watching this course and I've deployed a CentOS 6 VM with node, npm, and git installed.
Everything worked fine until the 'npm install' command where there were a few issues.
I tried playing around with the 'package.json' file to no success.
Do you have any recommendations on what I can do?

Output of 'npm install':
`[root@localhost angular2-essential-training]# npm cache clean
[root@localhost angular2-essential-training]# npm install
npm http GET https://registry.npmjs.org/angular/common/2.0.0
npm http GET https://registry.npmjs.org/angular/compiler/2.0.0
npm http GET https://registry.npmjs.org/angular/core/2.0.0
npm http GET https://registry.npmjs.org/angular/forms/2.0.0
npm http GET https://registry.npmjs.org/angular/http/2.0.0
npm http GET https://registry.npmjs.org/angular/platform-browser-dynamic/2.0.0
npm http GET https://registry.npmjs.org/angular/router/3.0.0
npm http GET https://registry.npmjs.org/angular/platform-browser/2.0.0
npm http GET https://registry.npmjs.org/systemjs/0.19.27
npm http GET https://registry.npmjs.org/core-js/2.4.1
npm http GET https://registry.npmjs.org/reflect-metadata/0.1.3
npm http GET https://registry.npmjs.org/types/core-js
npm http GET https://registry.npmjs.org/rxjs/5.0.0-beta.12
npm http GET https://registry.npmjs.org/types/node
npm http GET https://registry.npmjs.org/zone.js/0.6.23
npm http GET https://registry.npmjs.org/concurrently/2.2.0
npm http GET https://registry.npmjs.org/lite-server/2.2.2
npm http GET https://registry.npmjs.org/rimraf/2.5.4
npm http GET https://registry.npmjs.org/typescript/2.0.2
npm http 404 https://registry.npmjs.org/angular/common/2.0.0
npm http 404 https://registry.npmjs.org/angular/forms/2.0.0
npm http 404 https://registry.npmjs.org/angular/core/2.0.0
npm http 404 https://registry.npmjs.org/angular/compiler/2.0.0
npm http 404 https://registry.npmjs.org/angular/http/2.0.0
npm ERR! 404 'angular' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Linux 2.6.32-642.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /root/node/angular2-essential-training
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR! code E404
npm http 200 https://registry.npmjs.org/systemjs/0.19.27
npm http 200 https://registry.npmjs.org/core-js/2.4.1
npm http GET https://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz
npm http GET https://registry.npmjs.org/systemjs/-/systemjs-0.19.27.tgz
npm http 200 https://registry.npmjs.org/reflect-metadata/0.1.3
npm http 200 https://registry.npmjs.org/rxjs/5.0.0-beta.12
npm http GET https://registry.npmjs.org/reflect-metadata/-/reflect-metadata-0.1.3.tgz
npm http GET https://registry.npmjs.org/rxjs/-/rxjs-5.0.0-beta.12.tgz
npm http 200 https://registry.npmjs.org/systemjs/-/systemjs-0.19.27.tgz
npm http 200 https://registry.npmjs.org/core-js/-/core-js-2.4.1.tgz
npm http 200 https://registry.npmjs.org/reflect-metadata/-/reflect-metadata-0.1.3.tgz
npm http 200 https://registry.npmjs.org/rxjs/-/rxjs-5.0.0-beta.12.tgz
npm http 404 https://registry.npmjs.org/angular/platform-browser-dynamic/2.0.0
npm http 404 https://registry.npmjs.org/angular/platform-browser/2.0.0
npm http 404 https://registry.npmjs.org/angular/router/3.0.0
npm http 404 https://registry.npmjs.org/types/core-js
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-642.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /root/node/angular2-essential-training
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm http 404 https://registry.npmjs.org/types/node
npm ERR! TypeError: Cannot read property 'latest' of undefined
npm ERR!     at next (/usr/lib/node_modules/npm/lib/cache.js:687:35)
npm ERR!     at /usr/lib/node_modules/npm/lib/cache.js:675:5
npm ERR!     at saved (/usr/lib/node_modules/npm-registry-client/lib/get.js:148:7)
npm ERR!     at /usr/lib/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-642.el6.x86_64
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /root/node/angular2-essential-training
npm ERR! node -v v0.10.48
npm ERR! npm -v 1.3.6
npm ERR! type non_object_property_load
npm http 200 https://registry.npmjs.org/zone.js/0.6.23
npm http 200 https://registry.npmjs.org/concurrently/2.2.0
npm http GET https://registry.npmjs.org/zone.js/-/zone.js-0.6.23.tgz
npm http GET https://registry.npmjs.org/concurrently/-/concurrently-2.2.0.tgz
npm http 200 https://registry.npmjs.org/rimraf/2.5.4
npm http 200 https://registry.npmjs.org/typescript/2.0.2
npm http GET https://registry.npmjs.org/rimraf/-/rimraf-2.5.4.tgz
npm http GET https://registry.npmjs.org/typescript/-/typescript-2.0.2.tgz
npm http 200 https://registry.npmjs.org/lite-server/2.2.2
npm http GET https://registry.npmjs.org/lite-server/-/lite-server-2.2.2.tgz
npm http 200 https://registry.npmjs.org/concurrently/-/concurrently-2.2.0.tgz
npm http 200 https://registry.npmjs.org/rimraf/-/rimraf-2.5.4.tgz
npm http 200 https://registry.npmjs.org/typescript/-/typescript-2.0.2.tgz
npm http 200 https://registry.npmjs.org/lite-server/-/lite-server-2.2.2.tgz
npm http 200 https://registry.npmjs.org/zone.js/-/zone.js-0.6.23.tgz
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /root/node/angular2-essential-training/npm-debug.log
npm ERR! not ok code 0`

**Comment by christmerlini** [comment]
After some investigation, I noticed that the most up to date npm from the epel repo was at 1.3.6.
I followed this guide to add the node.js repo and everything works fine now.
http://tecadmin.net/install-latest-nodejs-and-npm-on-centos/#

I will close this issue.
